# Défi OB1  

_Elie Arnaud, Yvan LeBras_  

Git de l'équipe OB1 de l'Ocean Hackathon 2019 - Brest.  

## Description du défi

De plus en plus de données scientifiques sont aujourd'hui accessibles en accès ouvert. Cette mise à disposition est un premier pas essentiel vers un meilleur partage des connaissances et une réutilisation massives des données. Malheureusement, le partage du "matériel brut" ne suffit pas, et aujourd'hui plus que jamais se pose la question de la structuration de ces données. Comment faire en sorte que les données soient suffisamment bien décrites pour pouvoir être compréhensibles et réutilisées le plus largement possible ? Dans le cadre du projet "Pôle national de données de biodiversité", des actions en cours propose l'utilisation d'un standard de metadonnees, l'EML (Ecological Metadata Language), comme standard pivot d'outils et services qui faciliteraient cette structuration des données écologique et leur réutilisation. Des questionnements particuliers ont émergé concernant les données marines et ocean hackathon représente une initiative parfaite pour avancer sur certains aspects et laisser de potentiels hackers proposer d'améliorer ou/et créer des produits d'intérêt.  

**Objectifs**

En termes d'outils, nous travaillons sur le développement d'une application interactive R Shiny nommée (MetaSHARK)[https://github.com/earnaud/MetaShARK]. Nous aimerions développer des “modules” en R ou autre langage permettant d’automatiser les traitements de données marines hétérogènes pour par exemple parcourir des données d'écologie (séquences d'ADN ou données de présence d'espèces) et environnementales (données satellitaires ou autres données décrivant les conditions physico-chimiques du milieu) pour remplir de manière automatique et/ou assistée les champs de métadonnées pouvant l’être (étendues taxonomique, géographique et temporelle de l’étude ...).  

## Pistes envisagées

//TODO  
